apiVersion: v1
kind: Pod
metadata:
  name: agilghifari-pod
spec:
  initContainers:
    - name: volume-permissions
      image: busybox
      command: ["sh", "-c", "chown -R 1000:1000 /home/jovyan /workspace /home/jovyan/work && chmod -R 755 /home/jovyan /workspace /home/jovyan/work"]
      volumeMounts:
        - mountPath: "/home/jovyan"
          name: pvol-agilghifari
          subPath: jupyter-home
        - mountPath: "/workspace"
          name: pvol-agilghifari
        - mountPath: "/home/jovyan/work"
          name: pvol-agilghifari
          subPath: data
  containers:
    - name: agilghifari-container
      image: "syahrulapr/jupyterlab-pytorch-custom:latest"
      ports:
        - containerPort: 8888
        - containerPort: 9999
      env:
        - name: JUPYTER_TOKEN
          value: "my-token"
        - name: NVIDIA_VISIBLE_DEVICES
          value: "1"
        - name: NB_UID
          value: "1000"
        - name: NB_GID
          value: "1000"
      command: ["jupyter"]
      args: [
        "lab",
        "--ip=0.0.0.0",
        "--port=8888",
        "--no-browser",
        "--allow-root",
        "--notebook-dir=/workspace",
        "--LabApp.root_dir=/workspace"
      ]
      resources:
        limits:
          cpu: "16"
          memory: "32Gi"
          nvidia.com/gpu: 1
        requests:
          cpu: "500m"
          memory: "16Gi"
          nvidia.com/gpu: 1
      volumeMounts:
        - mountPath: "/workspace"
          name: pvol-agilghifari
        - mountPath: "/home/jovyan/work"
          name: pvol-agilghifari
          subPath: data
        - mountPath: "/home/jovyan"
          name: pvol-agilghifari
          subPath: jupyter-home
        - mountPath: "/opt/conda/envs"
          name: pvol-agilghifari
          subPath: conda-envs
        - mountPath: /dev/shm
          name: dshm
  volumes:
    - name: pvol-agilghifari
      persistentVolumeClaim:
        claimName: pvclaim-agilghifari
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 16Gi
